---
- name: debian | Installing DNSMasq
  apt:
    name: dnsmasq
    state: present
  become: true
  register: result
  until: result is succeeded

- name: debian | Install nmap
  apt:
    name: nmap
    state: present
  become: true
  register: result
  until: result is succeeded